// flow-typed signature: b9678caded15fc7d87823867acec40cd
// flow-typed version: <<STUB>>/chalk_v^2.1.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "chalk" {
  declare module.exports: any;
}

declare class chalk$chalk {
  static bold(string: string): string,
  static green(string: string): string,
  static underline(string: string): string,
  static gray(string: string): string,
  static red(string: string): string
}

declare module "chalk" {
  declare module.exports: Class<chalk$chalk>;
}
