// flow-typed signature: 084802012befacf35c375d0d5788f533
// flow-typed version: <<STUB>>/gulp-flowtype_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-flowtype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-flowtype' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-flowtype/declarations/child_process.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/flow-bin.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/flow-to-jshint.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/fs.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/gulp-util.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/index.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/jshint-stylish.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/log-symbols.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/path.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/pollyfill.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/q.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/declarations/through2.d' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/lib/index' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/test/fixtures/broken-interfaces/lib' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/test/fixtures/declaration' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/test/fixtures/hello' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/test/fixtures/interfaces/lib' {
  declare module.exports: any;
}

declare module 'gulp-flowtype/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-flowtype/declarations/child_process.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/child_process.d'>;
}
declare module 'gulp-flowtype/declarations/flow-bin.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/flow-bin.d'>;
}
declare module 'gulp-flowtype/declarations/flow-to-jshint.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/flow-to-jshint.d'>;
}
declare module 'gulp-flowtype/declarations/fs.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/fs.d'>;
}
declare module 'gulp-flowtype/declarations/gulp-util.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/gulp-util.d'>;
}
declare module 'gulp-flowtype/declarations/index.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/index.d'>;
}
declare module 'gulp-flowtype/declarations/jshint-stylish.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/jshint-stylish.d'>;
}
declare module 'gulp-flowtype/declarations/log-symbols.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/log-symbols.d'>;
}
declare module 'gulp-flowtype/declarations/path.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/path.d'>;
}
declare module 'gulp-flowtype/declarations/pollyfill.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/pollyfill.d'>;
}
declare module 'gulp-flowtype/declarations/q.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/q.d'>;
}
declare module 'gulp-flowtype/declarations/through2.d.js' {
  declare module.exports: $Exports<'gulp-flowtype/declarations/through2.d'>;
}
declare module 'gulp-flowtype/index' {
  declare module.exports: $Exports<'gulp-flowtype'>;
}
declare module 'gulp-flowtype/index.js' {
  declare module.exports: $Exports<'gulp-flowtype'>;
}
declare module 'gulp-flowtype/lib/index.js' {
  declare module.exports: $Exports<'gulp-flowtype/lib/index'>;
}
declare module 'gulp-flowtype/test/fixtures/broken-interfaces/lib.js' {
  declare module.exports: $Exports<'gulp-flowtype/test/fixtures/broken-interfaces/lib'>;
}
declare module 'gulp-flowtype/test/fixtures/declaration.js' {
  declare module.exports: $Exports<'gulp-flowtype/test/fixtures/declaration'>;
}
declare module 'gulp-flowtype/test/fixtures/hello.js' {
  declare module.exports: $Exports<'gulp-flowtype/test/fixtures/hello'>;
}
declare module 'gulp-flowtype/test/fixtures/interfaces/lib.js' {
  declare module.exports: $Exports<'gulp-flowtype/test/fixtures/interfaces/lib'>;
}
declare module 'gulp-flowtype/test/main.js' {
  declare module.exports: $Exports<'gulp-flowtype/test/main'>;
}
