// flow-typed signature: 43f89260fc00756dd072ee208234f840
// flow-typed version: <<STUB>>/terminal-menu_v^2.1.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terminal-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terminal-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terminal-menu/example/client' {
  declare module.exports: any;
}

declare module 'terminal-menu/example/menu' {
  declare module.exports: any;
}

declare module 'terminal-menu/example/server' {
  declare module.exports: any;
}

declare module 'terminal-menu/example/simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terminal-menu/example/client.js' {
  declare module.exports: $Exports<'terminal-menu/example/client'>;
}
declare module 'terminal-menu/example/menu.js' {
  declare module.exports: $Exports<'terminal-menu/example/menu'>;
}
declare module 'terminal-menu/example/server.js' {
  declare module.exports: $Exports<'terminal-menu/example/server'>;
}
declare module 'terminal-menu/example/simple.js' {
  declare module.exports: $Exports<'terminal-menu/example/simple'>;
}
declare module 'terminal-menu/index' {
  declare module.exports: $Exports<'terminal-menu'>;
}
declare module 'terminal-menu/index.js' {
  declare module.exports: $Exports<'terminal-menu'>;
}
