// flow-typed signature: b1376f17e91ebd65263c5530d8141544
// flow-typed version: <<STUB>>/xo_v^0.18.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xo/cli' {
  declare module.exports: any;
}

declare module 'xo/config/overrides' {
  declare module.exports: any;
}

declare module 'xo/config/plugins' {
  declare module.exports: any;
}

declare module 'xo/options-manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xo/cli.js' {
  declare module.exports: $Exports<'xo/cli'>;
}
declare module 'xo/config/overrides.js' {
  declare module.exports: $Exports<'xo/config/overrides'>;
}
declare module 'xo/config/plugins.js' {
  declare module.exports: $Exports<'xo/config/plugins'>;
}
declare module 'xo/index' {
  declare module.exports: $Exports<'xo'>;
}
declare module 'xo/index.js' {
  declare module.exports: $Exports<'xo'>;
}
declare module 'xo/options-manager.js' {
  declare module.exports: $Exports<'xo/options-manager'>;
}
